### ISSUE TITLE
second_script_var.sh

### ISSUE THREAD

**Issue by sham-glam** [sham-glam/PPE1#1]
Bonjour, 

Pour l'instant mes scripts ne fonctionnnent pas. 
Pour second_script il es possible que je me sois trompée pour sur le code

Plus important, je suis un peu perdue au niveau organisation de fichiers. 
Les programmes .bash  comptent le nombre  d'occurence de tel ou tel année, sur un certain type de fichier. 
Est-ce qu'il faut que ces fichiers .ann ou .txt soient dans le même dossier que les scripts bash pour pouvoir executer les tâches? 

Merci.

**Comment by YoannDupont** [comment]
Bonjour,

Dans vos scripts [second_script_var.sh](https://github.com/sham-glam/PPE1/blob/main/exercises/second_script_var.sh), vous utilisez des fichiers dans le dossier courant, c'est-à-dire le dossier où vous êtes quand vous lancez le script. Les fichiers recherchés ont un nom qui commence par l'année donnée en argument, par exemple `2016`.

Placez vous dans un dossier qui contient les fichiers `.ann` et tentez de lancer le script depuis ce dossier.

**Comment by sham-glam** [comment]
Bonjour, 

Merci pour votre réponse. 

Bien cordialement, 
Shami
